green-api:
  host: https://api.green-api.com
  hostMedia: https://media.green-api.com

spring:
  application:
    name: sw-chatbot-java-7103
  spring:
    config:
      import: optional:configserver:http://sw-prod-gateway.ru-central1.internal:8081

