green-api:
  host: https://7103.api.greenapi.com
  hostMedia: https://7103.media.greenapi.com
spring:
  config:
    import: optional:http://sw-prod-gateway.ru-central1.internal:8081/sw-chatbot-java-7103.yml